# Configurations
title: Siddhant Chaudhary
longtitle: Siddhant Chaudhary 
author: Siddhant Chaudhary
email: urssidd@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
    My personal webpage. Find out more about what I do on this site.

version:          1.0
gitbook_version:  3.2.3

url: "https://codetalker7.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
rss:              RSS

twitter_username: sid_codetalker7
github_username: codetalker7

# Build settings
remote_theme: sighingnow/jekyll-gitbook

toc:
  enabled: true
  h_min: 1
  h_max: 3

# markdown render engine
markdown:         kramdown
kramdown:
  auto_ids:               true
  input:                  GFM
  math_engine:            mathjax
  smart_quotes:           lsquo,rsquo,ldquo,rdquo
  toc_levels:             1..6
  syntax_highlighter:     rouge
  syntax_highlighter_opts:
    guess_lang:           true

syntax_highlighter_style: colorful

markdown_ext: markdown,mkdown,mkdn,mkd,md

# Permalinks
permalink: /:categories/:year-:month-:day-:title:output_ext

exclude:
  - _drafts

collections:
  pages:
    output: true
    sort_by: date
    permalink: /:collection/:path/

page_width: 800px

# google analytics
tracker:
    google_analytics: G-NCPKS7XPGR

destination:      ./_site
incremental:      false
regenerate:       true

plugins:
  - jekyll-feed
  - jekyll-readme-index
  - jemoji
